### ISSUE TITLE
I'm having troubles downloading TheHive 4 from repository. Apparently the certificate in https://deb.thehive-project.org is not valid?

### ISSUE THREAD

**Issue by erosseleth** [TheHive-Project/TheHive#2072]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian, Ubuntu, CentOS, RedHat, ...   |
| OS version (client)        | XP, Seven, 10, Ubuntu, ...            |
| Virtualized  Env.          | True / False                          |
| Dedicated RAM              | XX GB                                 |
| vCPU                       | 4 / 8 / 16 / 32                       |
| TheHive version / git hash | 4.x, hash of the commit               |
| Package Type               | RPM, DEB, Docker, Binary, From source |
| Database                   | Cassandra / BerlkelyDB                |
| Index type                 | Lucene / Elasticsearch                |
| Attachments storage        | Local, NFS, S3, HDFS                  |
| Browser type & version     | If applicable                         |

### Question

Describe the question/requirement as clearly as possible.

**Comment by erosseleth** [comment]
Sorry, clicked before give more data but i consider mostly irrelevant.

The process is:

curl https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY | sudo apt-key add -
echo 'deb https://deb.thehive-project.org release main' | sudo tee -a /etc/apt/sources.list.d/thehive-project.list
sudo apt update && sudo apt install thehive4 -y

And the result:

Hit:1 http://uy.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://uy.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                      
Hit:3 https://artifacts.elastic.co/packages/7.x/apt stable InRelease                                                                                                                          
Hit:5 http://uy.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                                                           
Hit:6 http://uy.archive.ubuntu.com/ubuntu focal-security InRelease              
Ign:7 https://deb.thehive-project.org release InRelease                         
Err:8 https://deb.thehive-project.org release Release                                                                 
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 135.125.31.131 443]
Hit:4 https://downloads.apache.org/cassandra/debian 311x InRelease                                                  
Reading package lists... Done
E: The repository 'https://deb.thehive-project.org release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by erosseleth** [comment]
Thanks @H2Cyber, that's i believe. I will wait bees actualize the certificate instead of doing an APT workaround. Hope it's fast.

**Comment by nadouani** [comment]
Should be fixed now

**Comment by nocomp** [comment]
> Sorry, clicked before give more data but i consider mostly irrelevant.
> 
> The process is:
> 
> curl https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY | sudo apt-key add - echo 'deb https://deb.thehive-project.org release main' | sudo tee -a /etc/apt/sources.list.d/thehive-project.list sudo apt update && sudo apt install thehive4 -y
> 
> And the result:
> 
> Hit:1 http://uy.archive.ubuntu.com/ubuntu focal InRelease Hit:2 http://uy.archive.ubuntu.com/ubuntu focal-updates InRelease Hit:3 https://artifacts.elastic.co/packages/7.x/apt stable InRelease Hit:5 http://uy.archive.ubuntu.com/ubuntu focal-backports InRelease Hit:6 http://uy.archive.ubuntu.com/ubuntu focal-security InRelease Ign:7 https://deb.thehive-project.org release InRelease Err:8 https://deb.thehive-project.org release Release Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate. Could not handshake: Error in the certificate verification. [IP: 135.125.31.131 443] Hit:4 https://downloads.apache.org/cassandra/debian 311x InRelease Reading package lists... Done E: The repository 'https://deb.thehive-project.org release Release' does not have a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details.

hi folks,
using ubuntu 20 and issue remains



Sorry, clicked before give more data but i consider mostly irrelevant.

The process is:

curl https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY | sudo apt-key add -
echo 'deb https://deb.thehive-project.org release main' | sudo tee -a /etc/apt/sources.list.d/thehive-project.list
sudo apt update && sudo apt install thehive4 -y

And the result:

Hit:1 http://uy.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://uy.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:5 http://uy.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:6 http://uy.archive.ubuntu.com/ubuntu focal-security InRelease
Ign:7 https://deb.thehive-project.org release InRelease
Err:8 https://deb.thehive-project.org release Release
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate. Could not handshake: Error in the certificate verification. [IP: 135.125.31.131 443]
Hit:4 https://downloads.apache.org/cassandra/debian 311x InRelease
Reading package lists... Done
E: The repository 'https://deb.thehive-project.org release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.


best regards
